services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 2s

  migration:
    build: .
    environment:
      - DATABASE_URL
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: python3 alembic/makesqlmigrations.py

  flyway:
    image: flyway/flyway
    volumes:
      - ./flyway:/flyway/db
      - ./sql:/flyway/sql
      - ./flyway:/flyway/conf
    depends_on:
      migration:
        condition: service_completed_successfully
        restart: true
    command: migrate

  app:
    build: .
    ports:
      - "8123:8000"
    environment:
      - DATABASE_URL
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
      flyway:
        condition: service_completed_successfully
        restart: true
