"""empty message

Revision ID: ae7f29e49b03
Revises: 4dc11366aefc
Create Date: 2025-10-20 16:39:51.707507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7f29e49b03'
down_revision: Union[str, Sequence[str], None] = '4dc11366aefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portals', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portals', 'logo')
    # ### end Alembic commands ###
